version: '3.8'

services:
  db:
    container_name: e-voting-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: e-voting-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: berkaydalancikar
    ports:
      - 5432:5432
  app:
    container_name: e-voting-api
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:berkaydalancikar@db:5432/todo-db
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 9001:9001
